### ISSUE TITLE
Fill out speaker form bug

### ISSUE THREAD

**Issue by jugaldb** [akshatvg/DevSoc-20#1]
https://i.imgur.com/nL6tqGd.gif

If you look it up in the gif attached, I can't access the speaker form at certain times due to the placement, I can when I move my mouse from top but when I do it from the bottom it just clicks on the next page button

**Comment by akshatvg** [comment]
@jugaldb what are your screen dimensions?

**Comment by akshatvg** [comment]
@jugaldb is it solved now?

**Comment by jugaldb** [comment]
Yes solved now, works perfectly well.

It was 
Screen Width: 1360 pixels
Screen Height: 765 pixels
